name: Coverage

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.14.1'
          registry-url: https://registry.npmjs.com/
          scope: '@mcdexio'

      - run: npm install
      # prepare ganache env
      - run: npm run start_testrpc

      - run: |
          git clone https://${CHECKOUT_PAT}@github.com/mcdexio/mai-protocol-v2.git
          cd mai-protocol-v2
          npm install
          npm run compile
          sed -i "s/migrations_directory.*/migrations_directory: \"test_migrations\",/g" truffle.js
          npm run migrate
          cd ${{ github.workspace }}
        env:
          ADDRESS_OUTPUT_PATH: '/tmp/addresses.json'
          WRAPPER_OUTPUT_PATH: ${{ github.workspace }}/tests/eth_address.ts
          CHECKOUT_PAT: ${{ secrets.CHECKOUT_PAT }}

      - run: npm test
